import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { connect } from 'react-redux';
import { getListUser } from '../redux/action/repos/creator';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <br/>
          <a href="https://github.com/zikriramdani/next-github-repo"
          target="_blank" rel="noopener noreferrer">Next.js with Github API (List Repo)!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/zikriramdani/next-github-repo"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Zikri Ramdani
        </a>
      </footer>
    </div>
  )
}
